[package]
name = "release-pls"
version = "0.1.0"
edition = "2021"
description = "Release to GitHub and crates.io"
repository = "https://github.com/MarcoIeni/release-pls"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
