[package]
name = "test_logs"
version = "0.1.0"
edition = "2021"
description = "Library to see logs in tests"
license = "MIT OR Apache-2.0"
repository = "https://github.com/MarcoIeni/release-plz/crates/test_logs"
keywords = ["test", "logs", "tracing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-log = "0.1"
